@baseURL=http://localhost:3000

# ============================================================
# 1. HEALTH
# ============================================================

###
GET {{baseURL}}/health HTTP/1.1

###
GET {{baseURL}}/health/live HTTP/1.1

###
GET {{baseURL}}/health/ready HTTP/1.1

###
GET {{baseURL}}/health/startup HTTP/1.1

###
GET {{baseURL}}/metrics HTTP/1.1