// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/capcom6",
            "email": "i@capcom.me"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/webhooks/omnidesk": {
            "post": {
                "description": "Accepts an authored webhook event, deduplicates it and enqueues it for processing",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "webhook"
                ],
                "summary": "Receive OmniDesk webhook",
                "parameters": [
                    {
                        "description": "Webhook payload",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/webhook.Request"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/fiberfx.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "fiberfx.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "webhook.Request": {
            "type": "object",
            "required": [
                "case_id",
                "event_type"
            ],
            "properties": {
                "case_description": {
                    "type": "string"
                },
                "case_group": {
                    "type": "string"
                },
                "case_id": {
                    "type": "integer"
                },
                "case_number": {
                    "type": "string"
                },
                "case_priority": {
                    "type": "string"
                },
                "case_status": {
                    "type": "string"
                },
                "case_subject": {
                    "type": "string"
                },
                "case_tags": {
                    "type": "string"
                },
                "case_url": {
                    "type": "string"
                },
                "event_type": {
                    "type": "string"
                },
                "last_message": {
                    "type": "string"
                },
                "last_message_id": {
                    "type": "string"
                },
                "note_text": {
                    "type": "string"
                },
                "staff_full_name": {
                    "type": "string"
                },
                "staff_id": {
                    "type": "string"
                },
                "user_email": {
                    "type": "string"
                },
                "user_full_name": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "user_lang": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Project API",
	Description:      "Project API documentation",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
